version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: camping_inventory_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: camping_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: