version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: horoscopo_efm5
    environment:
      POSTGRES_DB: horoscopo_efm5
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
