version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: universidad_db
    environment:
      POSTGRES_DB: universidad_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - universidad_data:/var/lib/postgresql/data

volumes:
  universidad_data: