spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5433/universidad_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    filter:
      order: 10
    user:
      name: admin
      password: admin123

jwt:
  secret: c3B9OBciuBQOq6N6GdO8dLMNMO1Uy16pnzBIpWp2
  expiration: 3600000
  refresh-expiration: 7200000

server:
  port: 8080