spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/universidad_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Cambiado de update a validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Configuración JWT
security:
  jwt:
    token:
      secret-key: tu_clave_secreta_muy_larga_y_segura_para_el_jwt_token_2024
      expire-length: 3600000 # 1 hora en milisegundos

# Configuración de logging
logging:
  level:
    root: INFO
    com.example.universidad: DEBUG